Install before testing
As this formula does not have commands for building from HEAD, the
package must be installed before it can be tested, as the following
message describes:

   $ brew test fc4.rb
   Error: Testing requires the latest version of fc4