Fix Homebrew audit errors
$ brew audit --strict fc4.rb
fc4:
  * C: 2: col 1: A `test do` test block should be added
  * C: 3: col 3: Description is too long. "name: desc" should be less than 80 characters. Length is calculated as fc4 + desc. (currently 89)
  * C: 3: col 8: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 3: col 9: Description shouldn't start with an indefinite article, i.e. "A"
  * C: 3: col 92: Description shouldn't end with a full stop
  * C: 4: col 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 5: col 11: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 8: col 9: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 9: col 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 11: col 9: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 12: col 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 16: col 14: Use hash rockets syntax.
  * C: 16: col 20: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 25: col 3: `install` (line 25) should be put before `caveats` (line 18)
  * C: 26: col 17: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 27: col 17: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 28: col 17: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 31: col 3: `resource` (line 31) should be put before `install` (line 25)
  * C: 31: col 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 32: col 9: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 33: col 12: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * C: 36: col 3: Use new-style test definitions (test do)
  * C: 37: col 14: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  * Stable: version 2019-07-26_1982 should not end with an underline and a number
  * Use `system "#{bin}/fc4", "-fs", "#{testpath}/fc4-tool-01-context.yaml"` instead of `system "#{bin}/fc4 -fs #{testpath}/fc4-tool-01-context.yaml"`
Error: 25 problems in 1 formula detected